spring:
  application:
    name: booking-service
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  cache:
    type: redis
    redis:
      time-to-live: 5m
      key-prefix: "booking-service:"
      cache-null-values: false
  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:http://config-server:8888
  data:
    jpa:
      repository:
        enabled: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
    ssl:
      enabled: false
  datasource:
    url: jdbc:postgresql://${NEON_HOST}/${NEON_DB}?sslmode=require&channelBinding=require
    username: ${NEON_USER}
    password: ${NEON_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    filter:
      dispatcher-types: async, error, forward, include, request
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_ADDRESS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: com.bookticket.booking_service.dto
        session.timeout.ms: 30000
        request.timeout.ms: 30000
server:
  port: 8084
logging:
  level:
    org.springframework.theater-service: DEBUG
management:
  server:
    port: 9094
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Booking Service Configuration
booking:
  redis:
    lock:
      # Key prefix for seat locks
      key-prefix: "lock:seat"
      ttl: 5m
      # Booking prefix for lock values
      booking-prefix: "booking"
      max-retries: 0
      retry-delay-ms: 100
  payment:
    polling:
      max-attempts: 15        # Maximum number of polling attempts
      interval-ms: 2000       # Interval between polls (2 seconds)
      timeout-ms: 300000       # Total timeout (5 minutes)

services:
  payment-url: "lb://payment-service"
  theater-url: "lb://theater-service"
  notification-url: "lb://notification-service"
